version: '3.9'

networks:
  inception_network:

volumes:
  shared-volume-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fbafica/data/mariadb
  
  shared-volume-wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fbafica/data/wordpress

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
      - shared-volume-mariadb:/var/lib/mysql
      - ./requirements/mariadb/tools:/tools
    restart: always
    networks:
      - inception_network


  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - shared-volume-wordpress:/var/www/html
      - ./requirements/wordpress/tools/entrypoint.sh:/home/entrypoint/entrypoint.sh
    restart: always
    networks:
      - inception_network


  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:80"
    volumes:
      - shared-volume-wordpress:/var/www/html
      - ./requirements/nginx/nginx-conf:/etc/nginx/http.d
    restart: always
    networks:
      - inception_network
