version: '3.9'

networks:
  inception_network:

volumes:
  shared-volume:

services:
  mariadb:
    container_name: mariadb
    image: mariadb_42_inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: wordpress
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    image: wordpress_42_inception
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - shared-volume:/var/www/html
      - ./requirements/wordpress/wordpress-conf/wp-config.php:/var/www/html/wp-config.php
    networks:
      - inception_network

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx_42_inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:80"
    volumes:
      - shared-volume:/var/www/html
      - ./requirements/nginx/nginx-conf:/etc/nginx/http.d
    networks:
      - inception_network
