version: '3.9'

networks:
  inception_network:

volumes:
  shared-volume:

services:
  mariadb:
    container_name: mariadb
    image: mariadb_42_inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - ./requirements/mariadb/mariadb-conf/init.sql:/var/lib/mysql/init.sql
      - ./requirements/mariadb/mariadb-conf/entrypoint.sh:/mariadb-conf/entrypoint.sh
      - ./requirements/mariadb/mariadb-conf/mariadb-server.cnf:/etc/my.cnf.d/mariadb-server.cnf
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    image: wordpress_42_inception
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - shared-volume:/var/www/html
      - ./requirements/wordpress/wordpress-conf/wp-config.php:/var/www/html/wp-config.php
    networks:
      - inception_network
    depends_on:
      - mariadb

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    image: nginx_42_inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:80"
    volumes:
      - shared-volume:/var/www/html
      - ./requirements/nginx/nginx-conf:/etc/nginx/http.d
    networks:
      - inception_network
